// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rdc
{
    [RdcResourceType("rdc:index:GCPInstance")]
    public partial class GCPInstance : Pulumi.ComponentResource
    {
        /// <summary>
        /// url of your running container
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a GCPInstance resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GCPInstance(string name, GCPInstanceArgs args, ComponentResourceOptions? options = null)
            : base("rdc:index:GCPInstance", name, args ?? new GCPInstanceArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class GCPInstanceArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The image you want to run
        /// </summary>
        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        /// <summary>
        /// The location to run your cloudrun container
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        public GCPInstanceArgs()
        {
            Location = "us-central1";
        }
    }
}
