# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .aws_instance import *
from .azure_instance import *
from .gcp_instance import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "rdc",
  "mod": "index",
  "fqn": "jaxxstorm_pulumi_rdc",
  "classes": {
   "rdc:index:AWSInstance": "AWSInstance",
   "rdc:index:AzureInstance": "AzureInstance",
   "rdc:index:GCPInstance": "GCPInstance"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "rdc",
  "token": "pulumi:providers:rdc",
  "fqn": "jaxxstorm_pulumi_rdc",
  "class": "Provider"
 }
]
"""
)
